apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-record-mysql
  labels:
    app: webook-record-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webook-record-mysql
  template:
    metadata:
    #  name: webook-record-mysql
      labels:
        app: webook-record-mysql
    spec:
      containers:
        - name: webook-record-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root   # 请更改为你自己的密码
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3308
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql # mysql存储位置固定的
      restartPolicy: Always
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: webook-mysql-pvc
